### ISSUE TITLE
error ” ‘CV_CPU_HAS_SUPPORT_SSE2’ 

### ISSUE THREAD

**Issue by alisonzhang88** [zanazakaryaie/fastGaussianBlur#2]
I downloaded the tutorial code and run the simd code in my x86 PC, got an error ” ‘CV_CPU_HAS_SUPPORT_SSE2’ was not declared in this scope”. I switched to run code on ARM platform, got a similar error ” ‘CV_CPU_HAS_SUPPORT_NEON’ was not declared in this scope”. Do you have any idea to solve it?

_the opencv environment I used below:_

General configuration for OpenCV 3.3.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /home/bongos/opencv_contrib-3.3.0/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2021-05-26T09:26:14Z
    Host:                        Linux 4.15.0-142-generic x86_64
    CMake:                       3.14.0
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
      SSE4_1 (2 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (7 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      YES
    C++11:                       YES
    C++ Compiler:                /usr/bin/c++  (ver 5.4.0)

**Comment by zanazakaryaie** [comment]
Hi @alisonzhang88 
In OpenCV 3.x, universal intrinsics can be accessed only internally (inside the library code). With version 4.x, they made them publicly available. So, uninstall your OpenCV and install version 4.x. Let me know if you still get the same error.

**Comment by zanazakaryaie** [comment]
Hi @alisonzhang88 
Did you observe the same error with OpenCV 4?

**Comment by alisonzhang88** [comment]
Hey, Zana

Yes, it works. Thank you so much.

Zana Zakaryaie Nejad ***@***.***> 于2021年10月1日周五 下午1:35写道：
